apiVersion: 1

datasources:
  - name: MymonPG
    uid: mymon-pg
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    user: $POSTGRES_RO_USER
    isDefault: true
    editable: false
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    secureJsonData:
      password: $POSTGRES_RO_PASSWORD
