"""Shared display labels for country_grocery.py, mirrors nl_metrics/eurostat_grocery's
PRODUCTS slugs on the collector side (same plain-literal-mirror pattern as
_nl_common.CPI_PRODUCT_LABELS — no import dependency on the collector package).

Not a dashboard script itself — generate_all.py skips any file starting with "_".
"""

PRODUCT_LABELS = {
    "rice": "Rice", "flours_and_other_cereals": "Flours & other cereals", "bread": "Bread",
    "other_bakery_products": "Other bakery products", "pizza_and_quiche": "Pizza & quiche",
    "pasta_products_and_couscous": "Pasta & couscous", "breakfast_cereals": "Breakfast cereals",
    "other_cereal_products": "Other cereal products", "beef_and_veal": "Beef & veal",
    "pork": "Pork", "lamb_and_goat": "Lamb & goat", "poultry": "Poultry",
    "other_meats": "Other meats", "edible_offal": "Edible offal",
    "dried_salted_or_smoked_meat": "Dried/salted/smoked meat",
    "other_meat_preparations": "Other meat preparations",
    "fresh_or_chilled_fish": "Fresh/chilled fish", "frozen_fish": "Frozen fish",
    "fresh_or_chilled_seafood": "Fresh/chilled seafood", "frozen_seafood": "Frozen seafood",
    "dried_smoked_or_salted_fish_and_seafood": "Dried/smoked/salted fish & seafood",
    "other_preserved_or_processed_fish_and_seafood": "Other preserved fish & seafood",
    "fresh_whole_milk": "Fresh whole milk", "fresh_low_fat_milk": "Fresh low-fat milk",
    "preserved_milk": "Preserved milk", "yoghurt": "Yoghurt",
    "cheese_and_curd": "Cheese & curd", "other_milk_products": "Other milk products",
    "eggs": "Eggs", "butter": "Butter",
    "margarine_and_other_vegetable_fats": "Margarine & vegetable fats",
    "olive_oil": "Olive oil", "other_edible_oils": "Other edible oils",
    "other_edible_animal_fats": "Other edible animal fats",
    "fresh_or_chilled_fruit": "Fresh/chilled fruit", "frozen_fruit": "Frozen fruit",
    "dried_fruit_and_nuts": "Dried fruit & nuts",
    "preserved_fruit_and_fruit_based_products": "Preserved fruit products",
    "fresh_or_chilled_vegetables": "Fresh/chilled vegetables",
    "frozen_vegetables": "Frozen vegetables",
    "dried_or_preserved_vegetables": "Dried/preserved vegetables", "potatoes": "Potatoes",
    "crisps": "Crisps", "other_tubers_and_products": "Other tubers & products",
    "sugar": "Sugar", "jams_marmalades_and_honey": "Jams, marmalade & honey",
    "chocolate": "Chocolate", "confectionery_products": "Confectionery",
    "edible_ices_and_ice_cream": "Ice cream",
    "artificial_sugar_substitutes": "Artificial sweeteners",
    "sauces_condiments": "Sauces & condiments",
    "salt_spices_and_culinary_herbs": "Salt, spices & herbs", "baby_food": "Baby food",
    "ready_made_meals": "Ready meals", "other_food_products": "Other food products",
    "coffee": "Coffee", "tea": "Tea",
    "cocoa_and_powdered_chocolate": "Cocoa powder",
    "mineral_or_spring_waters": "Mineral water", "soft_drinks": "Soft drinks",
    "fruit_and_vegetable_juices": "Fruit & vegetable juices",
}

# Mirrors eurostat_cost_of_living.CATEGORIES slugs on the collector side.
COST_OF_LIVING_LABELS = {
    "food_and_drink": "Food & non-alc. drink",
    "alcohol_and_tobacco": "Alcohol & tobacco",
    "clothing_and_footwear": "Clothing & footwear",
    "housing_water_energy": "Housing, water & energy",
    "furnishings_household": "Furnishings & household",
    "health": "Health",
    "transport": "Transport",
    "communication": "Communication",
    "recreation_and_culture": "Recreation & culture",
    "education": "Education",
    "restaurants_and_hotels": "Restaurants & hotels",
    "misc_goods_and_services": "Misc. goods & services",
}


# Mirrors eurostat_regional.py's region codes (NUTS2), one label per code — sourced live
# from Eurostat's own geo dimension labels, not maintained by hand.
REGION_LABELS = {
    "DE11": "Stuttgart",
    "DE12": "Karlsruhe",
    "DE13": "Freiburg",
    "DE14": "Tübingen",
    "DE21": "Oberbayern",
    "DE22": "Niederbayern",
    "DE23": "Oberpfalz",
    "DE24": "Oberfranken",
    "DE25": "Mittelfranken",
    "DE26": "Unterfranken",
    "DE27": "Schwaben",
    "DE30": "Berlin",
    "DE40": "Brandenburg",
    "DE50": "Bremen",
    "DE60": "Hamburg",
    "DE71": "Darmstadt",
    "DE72": "Gießen",
    "DE73": "Kassel",
    "DE80": "Mecklenburg-Vorpommern",
    "DE91": "Braunschweig",
    "DE92": "Hannover",
    "DE93": "Lüneburg",
    "DE94": "Weser-Ems",
    "DEA1": "Düsseldorf",
    "DEA2": "Köln",
    "DEA3": "Münster",
    "DEA4": "Detmold",
    "DEA5": "Arnsberg",
    "DEB1": "Koblenz",
    "DEB2": "Trier",
    "DEB3": "Rheinhessen-Pfalz",
    "DEC0": "Saarland",
    "DED2": "Dresden",
    "DED4": "Chemnitz",
    "DED5": "Leipzig",
    "DEE0": "Sachsen-Anhalt",
    "DEF0": "Schleswig-Holstein",
    "DEG0": "Thüringen",
    "EL30": "Attiki",
    "EL41": "Voreio Aigaio",
    "EL42": "Notio Aigaio",
    "EL43": "Kriti",
    "EL51": "Anatoliki Makedonia, Thraki",
    "EL52": "Kentriki Makedonia",
    "EL53": "Dytiki Makedonia",
    "EL54": "Ipeiros",
    "EL61": "Thessalia",
    "EL62": "Ionia Nisia",
    "EL63": "Dytiki Elláda",
    "EL64": "Sterea Elláda",
    "EL65": "Peloponnisos",
    "ES11": "Galicia",
    "ES12": "Principado de Asturias",
    "ES13": "Cantabria",
    "ES21": "País Vasco",
    "ES22": "Comunidad Foral de Navarra",
    "ES23": "La Rioja",
    "ES24": "Aragón",
    "ES30": "Comunidad de Madrid",
    "ES41": "Castilla y León",
    "ES42": "Castilla-La Mancha",
    "ES43": "Extremadura",
    "ES51": "Cataluña",
    "ES52": "Comunitat Valenciana",
    "ES53": "Illes Balears",
    "ES61": "Andalucía",
    "ES62": "Región de Murcia",
    "ES63": "Ciudad de Ceuta",
    "ES64": "Ciudad de Melilla",
    "ES70": "Canarias",
    "FR10": "Ile de France",
    "FRB0": "Centre — Val de Loire",
    "FRC1": "Bourgogne",
    "FRC2": "Franche-Comté",
    "FRD1": "Basse-Normandie",
    "FRD2": "Haute-Normandie",
    "FRE1": "Nord-Pas de Calais",
    "FRE2": "Picardie",
    "FRF1": "Alsace",
    "FRF2": "Champagne-Ardenne",
    "FRF3": "Lorraine",
    "FRG0": "Pays de la Loire",
    "FRH0": "Bretagne",
    "FRI1": "Aquitaine",
    "FRI2": "Limousin",
    "FRI3": "Poitou-Charentes",
    "FRJ1": "Languedoc-Roussillon",
    "FRJ2": "Midi-Pyrénées",
    "FRK1": "Auvergne",
    "FRK2": "Rhône-Alpes",
    "FRL0": "Provence-Alpes-Côte d’Azur",
    "FRM0": "Corse",
    "FRY1": "Guadeloupe",
    "FRY2": "Martinique",
    "FRY3": "Guyane",
    "FRY4": "La Réunion",
    "FRY5": "Mayotte",
    "ITC1": "Piemonte",
    "ITC2": "Valle d’Aosta/Vallée d’Aoste",
    "ITC3": "Liguria",
    "ITC4": "Lombardia",
    "ITF1": "Abruzzo",
    "ITF2": "Molise",
    "ITF3": "Campania",
    "ITF4": "Puglia",
    "ITF5": "Basilicata",
    "ITF6": "Calabria",
    "ITG1": "Sicilia",
    "ITG2": "Sardegna",
    "ITH1": "Provincia Autonoma di Bolzano/Bozen",
    "ITH2": "Provincia Autonoma di Trento",
    "ITH3": "Veneto",
    "ITH4": "Friuli-Venezia Giulia",
    "ITH5": "Emilia-Romagna",
    "ITI1": "Toscana",
    "ITI2": "Umbria",
    "ITI3": "Marche",
    "ITI4": "Lazio",
    "TR10": "İstanbul",
    "TR21": "Tekirdağ, Edirne, Kırklareli",
    "TR22": "Balıkesir, Çanakkale",
    "TR31": "İzmir",
    "TR32": "Aydın, Denizli, Muğla",
    "TR33": "Manisa, Afyonkarahisar, Kütahya, Uşak",
    "TR41": "Bursa, Eskişehir, Bilecik",
    "TR42": "Kocaeli, Sakarya, Düzce, Bolu, Yalova",
    "TR51": "Ankara",
    "TR52": "Konya, Karaman",
    "TR61": "Antalya, Isparta, Burdur",
    "TR62": "Adana, Mersin",
    "TR63": "Hatay, Kahramanmaraş, Osmaniye",
    "TR71": "Kırıkkale, Aksaray, Niğde, Nevşehir, Kırşehir",
    "TR72": "Kayseri, Sivas, Yozgat",
    "TR81": "Zonguldak, Karabük, Bartın",
    "TR82": "Kastamonu, Çankırı, Sinop",
    "TR83": "Samsun, Tokat, Çorum, Amasya",
    "TR90": "Trabzon, Ordu, Giresun, Rize, Artvin, Gümüşhane",
    "TRA1": "Erzurum, Erzincan, Bayburt",
    "TRA2": "Ağrı, Kars, Iğdır, Ardahan",
    "TRB1": "Malatya, Elazığ, Bingöl, Tunceli",
    "TRB2": "Van, Muş, Bitlis, Hakkari",
    "TRC1": "Gaziantep, Adıyaman, Kilis",
    "TRC2": "Şanlıurfa, Diyarbakır",
    "TRC3": "Mardin, Batman, Şırnak, Siirt",
}

# Mirrors eurostat_metrics.AGE_BRACKETS.
AGE_BRACKET_LABELS = {
    "10_14": "10-14", "15_19": "15-19", "20_24": "20-24", "25_29": "25-29",
    "30_34": "30-34", "35_39": "35-39", "40_44": "40-44", "45_49": "45-49",
    "50_plus": "50+",
}
