#!/bin/bash
# Creates the read-only role used by Grafana. Runs once on first init.
set -euo pipefail

: "${POSTGRES_RO_USER:=grafana_ro}"
: "${POSTGRES_RO_PASSWORD:?POSTGRES_RO_PASSWORD must be set}"

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE ${POSTGRES_RO_USER} LOGIN PASSWORD '${POSTGRES_RO_PASSWORD}';
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_RO_USER};
  GRANT USAGE ON SCHEMA public TO ${POSTGRES_RO_USER};
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${POSTGRES_RO_USER};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
    GRANT SELECT ON TABLES TO ${POSTGRES_RO_USER};
  ALTER ROLE ${POSTGRES_RO_USER} SET default_transaction_read_only = on;
  ALTER ROLE ${POSTGRES_RO_USER} SET statement_timeout = '30s';
EOSQL
